### ISSUE TITLE
Publishing Music Theory Package

### ISSUE THREAD

**Issue by Evelios** [duncanmalashock/music-theory#1]
I have been working on a very similar package to yours and stumbled across it trying to do research to see if there was anything similar out there. I have noticed that there are several repositories out there that you have worked on in the past. It seems like this one is the most complete and is still being updated. This package is far beyond where I have gotten and has incorporated some better design choices than mine has. I was wondering if you had interest in deploying this package to the elm package repository. If you were what milestones have you not reached that are preventing you from getting there? The biggest one I see would be that all the packages would need added documentation so that the users would be able to see what is available.

**Comment by duncanmalashock** [comment]
Hi @Evelios, thanks! And yes, I will definitely be publishing this package when it's ready for a first release. Hopefully that's not too far off!

In the meantime, I'm going to be working solo on the design decisions for this project, but thank you for the PR and your enthusiasm.

**Comment by Evelios** [comment]
I absolutely understand and respect your decisions on retaining solo ownership of design decisions of the project. That being said, if you have the API flushed out in a particular area I would be willing to help out filling in some of the logic. In the mean time, I'll probably be using a fork of your project for my work because your work seems very well though out and polished in terms of API design so far and look forward to your eventual work. Good luck!

**Comment by duncanmalashock** [comment]
@Evelios thanks very much for the offer! I'll keep you in mind.

I've added some more information in the README and CONTRIBUTING files of this repo. If you're interested in sharing more details about your project, please feel free to reach out to me on the [Elm Slack](https://elmlang.herokuapp.com/) at `@duncan` and tell me about your use case. I'll do my best to support it if I can.
